# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.TextField(default='investor', null=True),
        ),
    ]
