# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealgradermodel',
            name='appeal_by_user',
        ),
        migrations.RemoveField(
            model_name='appealgradermodel',
            name='appeal_grader',
        ),
        migrations.RemoveField(
            model_name='appealgradermodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='appealgradermodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='coursehomeworkmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='groupcombinationmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groupcombinationmodel',
            name='grader_group',
        ),
        migrations.RemoveField(
            model_name='groupcombinationmodel',
            name='grader_user',
        ),
        migrations.RemoveField(
            model_name='groupcombinationmodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupcombinationmodel',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='homeworkgroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homeworkgroup',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='homeworkgroupgrade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='homeworkgroupgrade',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homeworkgroupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homeworkgroupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='peerevaluationmodel',
            name='appeal_grader',
        ),
        migrations.RemoveField(
            model_name='peerevaluationmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='peerevaluationmodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='peerevaluationmodel',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='peerevaluationmodel',
            name='peer_grader',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrolledmodel',
            name='course',
        ),
        migrations.DeleteModel(
            name='AppealGraderModel',
        ),
        migrations.DeleteModel(
            name='CourseHomeWorkModel',
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='GroupCombinationModel',
        ),
        migrations.DeleteModel(
            name='HomeworkGroup',
        ),
        migrations.DeleteModel(
            name='HomeworkGroupGrade',
        ),
        migrations.DeleteModel(
            name='HomeworkGroupMember',
        ),
        migrations.DeleteModel(
            name='PeerEvaluationModel',
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrolledModel',
        ),
    ]
